#' @param table Merged obs & ref CNV score matrix generated by inferCNV. # nolint
processMatrix <- function(table) # nolint
{
    library(magrittr)
    cnv_score_mat <- as.matrix(table)
    cnv_score_table <- as.matrix(table)
    cnv_score_table <- cnv_score_table %>% t() %>% scale() %>% scales::rescale(to = c(-1, 1)) %>% t() # nolint
    cnv_score_table <- as.matrix(as.data.frame(cnv_score_table * cnv_score_table)) # nolint 
    res <- list(cnv_score_mat, cnv_score_table)
    names(res) <- c("mat", "table")
    return(res)
}

#' @param table Merged observation & ref CNV score matrix generated by inferCNV.
#' @param adj_cells Cells names from tumor-adjacent tissues
#' @param tumor_cells Cells names from tumor-sourced tissues
MeanExpect <- function(table, adj_cells, tumor_cells) # nolint
{
    res <- list()
    t1 <- processMatrix(table)
    ## calculate median cnv score
    adj_table <- t1[["table"]][, adj_cells]
    tumor_table <- t1[["table"]][, tumor_cells]
    adj_expect <- floor(mean(colSums(adj_table)))
    tumor_expect <- floor(mean(colSums(tumor_table)))
    print(paste("mean normal cnv score expect:", adj_expect))
    print(paste("mean tumor cnv score expect:", tumor_expect))
    res[["processed.data"]] <- t1
    res[["norm.expect"]] <- adj_expect
    res[["mali.expect"]] <- tumor_expect
    return(res)
}

#' @param raw_expect Result list obj generated by 'MeanExpect' function.
#' @param adj_cells Cells names from tumor-adjacent tissues
#' @param tumor_cells Cells names from tumor-sourced tissues
ExpectCorrection <- function(raw_expect, adj_cells, tumor_cells) # nolint
{
    raw_norm_expect <- raw_expect[["norm.expect"]]
    raw_mali_expect <- raw_expect[["mali.expect"]]
    raw_norm_cell_cnvscores <- data.frame(cnvscores = colSums(raw_expect[["processed.data"]][["table"]][, adj_cells])) # nolint
    raw_mali_cell_cnvscores <- data.frame(cnvscores = colSums(raw_expect[["processed.data"]][["table"]][, tumor_cells])) # nolint
    median_norm_expect <- floor(median(raw_norm_cell_cnvscores[["cnvscores"]]))
    median_mali_expect <- floor(median(raw_mali_cell_cnvscores[["cnvscores"]]))
    folder <- floor(raw_mali_expect / raw_norm_expect)
    up_threshold <- floor(raw_mali_expect / folder)
    down_threshold <- ceiling(raw_norm_expect * folder)
    norm_ratios <- sum(raw_norm_cell_cnvscores[["cnvscores"]] <= up_threshold) / length(raw_norm_cell_cnvscores[["cnvscores"]]) # nolint
    mali_ratios <- sum(raw_mali_cell_cnvscores[["cnvscores"]] >= down_threshold) / length(raw_mali_cell_cnvscores[["cnvscores"]]) # nolint
    choose_flag_norm <- ifelse(norm_ratios >= 0.7, "converge_method", "median")
    choose_flag_mali <- ifelse(mali_ratios >= 0.7, "converge_method", "median")
    converge <- ifelse(any(raw_norm_cell_cnvscores[["cnvscores"]] >= up_threshold) | (any(raw_mali_cell_cnvscores[["cnvscores"]] <= down_threshold)), FALSE, TRUE) # nolint
    while(!converge)
    {
        raw_norm_cell_cnvscores[["use"]] <- ifelse(raw_norm_cell_cnvscores[["cnvscores"]] >= up_threshold, "False", "True") # nolint
        raw_mali_cell_cnvscores[["use"]] <- ifelse(raw_mali_cell_cnvscores[["cnvscores"]] <= down_threshold, "False", "True") # nolint
        norm_expect.correct <- floor(mean(raw_norm_cell_cnvscores[["cnvscores"]][which(raw_norm_cell_cnvscores[["use"]] == "True")])) # nolint
        mali_expect.correct <- floor(mean(raw_mali_cell_cnvscores[["cnvscores"]][which(raw_mali_cell_cnvscores[["use"]] == "True")])) # nolint
        folder <- floor(mali_expect.correct / norm_expect.correct)
        converge <- ifelse(any(raw_norm_cell_cnvscores[["cnvscores"]][which(raw_norm_cell_cnvscores[["use"]] == "True")] >= up_threshold) | (any(raw_mali_cell_cnvscores[["cnvscores"]][which(raw_mali_cell_cnvscores[["use"]] == "True")] <= down_threshold)), FALSE, TRUE) # nolint
    }
    norm_expect.correct <- ifelse(choose_flag_norm == "converge_method", norm_expect.correct, median_norm_expect) # nolint
    mali_expect.correct <- ifelse(choose_flag_mali == "converge_method", mali_expect.correct, median_mali_expect) # nolint
    print(paste0("corrected normal cnv score:", norm_expect.correct))
    print(paste0("corrected malignant cnv score:", mali_expect.correct))
    raw_expect[["norm.expect"]] <- norm_expect.correct
    raw_expect[["mali.expect"]] <- mali_expect.correct
    raw_expect[["norm.cnv_score_per_cell"]] <- raw_norm_cell_cnvscores
    raw_expect[["mali.cnv_score_per_cell"]] <- raw_mali_cell_cnvscores
    return(raw_expect)
}

#' @param table Merged observation & ref CNV score matrix generated by inferCNV
#' @param k_groups The number of clusters to group
#' @param iteration The maximum recursion number
CellDiscern <- function(table, k_groups, iteration = 2) # nolint
{
    mat_table <- processMatrix(table)
    t1 <- Reclustering(mat_table$mat, cells = colnames(mat_table$mat), clust_m = "ward.D2", k_groups = k_groups) # nolint
    res <- OutlierCapture(mat_table$table, t1[[1]], t1[[2]]) # nolint
    norm_cells <- res$norm
    mali_cells <- res$mali
    int_cells_tmp <- res$int
    if(length(int_cells_tmp) > 0)
    {
        count <- 0
        while(count < iteration)
        {
            print(paste("not converge, iteration step:", as.character(count + 1))) # nolint
            t2 <- Reclustering(mat_table$mat, cells = int_cells_tmp, clust_m = "ward.D2", k_groups = k_groups) # nolint
            tmp <- OutlierCapture(mat_table$table, t2[[1]], out.id = t2[[2]]) # nolint
            print(paste(as.character(count + 1), "round discerned normal cells:", as.character(length(tmp$norm)))) # nolint
            print(paste(as.character(count + 1)," round discerned malignant cells:", as.character(length(tmp$mali))));  # nolint
            print(paste(as.character(count + 1)," round discerned temporary intermediate cells:", as.character(length(tmp$int)))) # nolint
            norm_cells <- c(norm_cells, tmp$norm)
            mali_cells <- c(mali_cells, tmp$mali)
            if(length(tmp$int) == 0)
            {
                final_res <- list(norm_cells, mali_cells)
                names(final_res) <- c("pdNormal", "pdMalignant")
                return(final_res)
            }
            else if(length(tmp$norm) == 0 && length(tmp$mali) == 0)
            {
                final_res <- list(norm_cells, mali_cells, int_cells_tmp)
                names(final_res) <- c("pdNormal", "pdMalignant", "pdIntermediate") # nolint
                return(final_res)
            }else
            {
                count <- count + 1
                int_cells_tmp <- tmp$int
            }
        }
        final_res <- list(norm_cells, mali_cells, int_cells_tmp)
        names(final_res) <- c("pdNormal", "pdMalignant", "pdIntermediate")
        return(final_res)
    }else
    {
        final_res <- list(norm_cells, mali_cells)
        names(final_res) <- c("pdNormal", "pdMalignant")
        return(final_res)
    }
}
#' @param cnv_score_mat Merged observation & ref CNV score matrix generated by inferCNV # nolint
#' @param cells The name of cells to clusters.
#' @param clust_m The clustering method, default is "ward.D2"
#' @param k_groups The number of clusters to group
Reclustering <- function(cnv_score_mat, cells, clust_m = 'ward.D2', k_groups = 10) # nolint
{
    mat <- cnv_score_mat[, cells]
    dists <- parallelDist::parallelDist(t(mat), method = "euclidean")
    t <- fastcluster::hclust(dists, method = clust_m)
    out.id <- cutree(t, k = k_groups) # nolint
    new.df <- as.data.frame(out.id) # nolint
    return(list(new.df, out.id))
}
#' @param cnv_score_table the normalised CNV score table generated by "processMatrix" function # nolint
#' @param new.df the cluster mapping results generated by "Reclustering" function # nolint
#' @param out.id the cluster id generated by "Reclustering" method
#' note that norm_expect_num & mali_expect_num are global variables.
OutlierCapture <- function(cnv_score_table, new.df, out.id) # nolint
{
    cnv_score_table <- cnv_score_table[, rownames(new.df)]
    cell_scores_CNV <- as.data.frame(colSums(cnv_score_table)) # nolint
    colnames(cell_scores_CNV) <- "cnv_score" # nolint
    new.df <- new.df[rownames(cell_scores_CNV), ] # nolint
    cell_scores_CNV$group <- new.df # nolint
    a1 <- aggregate(cell_scores_CNV$cnv_score, 
                    by = list(cell_scores_CNV$group), sum)
    groups <- as.data.frame(table(out.id))
    group_avg <- a1$x / groups$Freq
    print(group_avg)
    idx_norm <- seq(seq_along(group_avg))[group_avg <= norm_expect_num]
    idx_mali <- seq(seq_along(group_avg))[group_avg >= mali_expect_num]
    idx_int_tmp <- seq(seq_along(group_avg))[group_avg > norm_expect_num && group_avg < mali_expect_num] ## nolint
    norm_cells <- rownames(cell_scores_CNV[cell_scores_CNV$group %in% idx_norm,]) # nolint
    mali_cells <- rownames(cell_scores_CNV[cell_scores_CNV$group %in% idx_mali,]) # nolint
    int_tmp_cells <- rownames(cell_scores_CNV[cell_scores_CNV$group %in% idx_int_tmp,]) # nolint
    res <- list(norm_cells, mali_cells, int_tmp_cells)
    names(res) <- c("norm", "mali", "int")
    return(res)
}
