rm(list = ls())
gc()
setwd("YOURWORKDIR")
library(Seurat)
library(data.table)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
library(ggprism)
library(clusterProfiler)
library(org.Mm.eg.db)
source("./difgenes_tpm_funcs.R")

seob_10x <- readRDS(file = "./10X/brain_seob.rds")
seob_mw3 <- readRDS(file = "./brain_seob.rds")
counts_mw3 <- GetAssayData(seob_mw3, slot = "counts" assay = "RNA")
counts_10x <- GetAssayData(seob_10x, slot = "counts", assay = "RNA")
use_genes <- intersect(rownames(counts_mw3), rownames(counts_10x))

###### example #####
mw3_mature_neurons <- sampling(counts_mw3[, rownames(seob_mw3@meta.data)[seob_mw3$celltypes=="Mature neurons",]])
x10_neurons <- sampling(counts_10x[rownames(seob_10x@meta.data[seob_10X$anno  %in% c("Immature neurons", "Mature neurons"),])])
tpm_mature_neurons <- tpm_norm(mw3_mature_neurons, x10_neurons, use_genes)
diff_mature_neurons <- diffGenes(tpm_mature_neurons, 0.01, 2, type = "Mature neurons")
mean_mature_neurons <- MeanTpm(tpm_mature_neurons)